### ISSUE TITLE
[Textgrid for dataset]

### ISSUE THREAD

**Issue by frank269** [NTT123/vietTTS#1]
I am creating textgrid files for my dataset. Can you guide me how to create that file? Or you can give me information. Thank you so much!

**Comment by NTT123** [comment]
Hi @frank269 , I used Montreal Forced Aligner to create textgrid files. Visit https://montreal-forced-aligner.readthedocs.io/en/latest/ for more information.

**Comment by frank269** [comment]
thank for your response.

**Comment by frank269** [comment]
I used MFA 2.0 to align the text, but it through the error. How can i generate lexicon for vietnamese?
This is an error:
montreal_forced_aligner.exceptions.PronunciationAcousticMismatchError: There were phones in the dictionary that do not have acoustic models: a, e, i, u, y, ê, ề

**Comment by NTT123** [comment]
The pretrained acoustic model does not include these phones, in this case, you have to train your own acoustic model. See https://montreal-forced-aligner.readthedocs.io/en/latest/aligning.html#align-using-only-the-data-set for more information.

**Comment by frank269** [comment]
I tried using the first 6 files and the lexicon file in infore data to align and train with the command: 
./bin/mfa_train_and_align MFA/dataset MFA/lexicon.txt MFA/aligned
But it only has the first file that has the correct textgrid file, and the other files that give the wrong data, Where did I go wrong?

**Comment by NTT123** [comment]
To train a MFA model, you need: a lexicon file, a wav/text data directory.
The wav/text data directory includes all your audio clips and the transcript files. Each `A.wav` clip requires a `A.txt` transcript file in the same directory.

**Comment by frank269** [comment]
Yes, I used the first 6 files and lexicon file in the database infore you provided, I also manually created 6 transcription files for each audio clips. But when I run command train, the output of the first file is correct, but the other files are wrong, here are the results of the first 6 files:
[1.zip](https://github.com/NTT123/vietTTS/files/6603548/1.zip)

**Comment by NTT123** [comment]
It is possible that your dataset is too small, so MFA cannot learn a useful model from that little data.

**Comment by NTT123** [comment]
This is a notebook that I used to align InfoRe data with a slightly different phoneme set
https://colab.research.google.com/gist/NTT123/95b12ca42a4bdd1a856aba0fbb0f8936/infore-mfa-tutorial.ipynb

**Comment by frank269** [comment]
Oh, thank you so much!

**Comment by Lethanhson9901** [comment]
> This is a notebook that I used to align InfoRe data with a slightly different phoneme set
> https://colab.research.google.com/gist/NTT123/95b12ca42a4bdd1a856aba0fbb0f8936/infore-mfa-tutorial.ipynb

I'm using your colab script but I got issue:
![image](https://user-images.githubusercontent.com/49090718/122321159-9c800880-cf4d-11eb-909e-403705b4a58f.png)

I try to fix but I don't know what happend in MFA aligner. This is example of my lexicon textGrid and txt file
![lexicon](https://user-images.githubusercontent.com/49090718/122321271-cb967a00-cf4d-11eb-86ac-06841a83359a.png)
![textGrid](https://user-images.githubusercontent.com/49090718/122321292-d3561e80-cf4d-11eb-8125-fa3dc59abf77.png)
![txt](https://user-images.githubusercontent.com/49090718/122321311-da7d2c80-cf4d-11eb-81f5-de6f87985599.png)

And this is my tree:
![tree](https://user-images.githubusercontent.com/49090718/122321471-1e703180-cf4e-11eb-95f8-32b06141e02a.png)

Thanks!
