### ISSUE TITLE
Problems with Special Phonemes

### ISSUE THREAD

**Issue by phanan9225** [NTT123/vietTTS#12]
Hi,
I have trained with my own dataset, and the results look good. However, I face a problem with special phonemes. The TTS does not stop when meeting special phonemes  (in case setting silence_duration = 0) and sometimes it speaks some noise. When setting silence_duration =0.1 or higher, the TTS always speaks noise.
I guess something goes wrong with my *.textgrid files because there are no sil or sp phones in these. (https://drive.google.com/drive/folders/1RAsq-qPMjHMn-seJy3iapWAmLmjwz9nb?usp=sharing) And I have no idea to fix it.
This is my demo: http://6640-113-161-90-253.ngrok.io/
Can you give me some advice?
Thank you.

**Comment by NTT123** [comment]
You can use the ``Praat`` program to visualize your textgrid + audio pair.
https://www.fon.hum.uva.nl/praat/

**Comment by phanan9225** [comment]
Thank you, I'll try this.
