### ISSUE TITLE
High RAM usage acoustic model

### ISSUE THREAD

**Issue by lethanhson9901** [NTT123/vietTTS#14]
After MFA training, I've got 39778 Textgrids and 39778 wav file. The issue that when I ran acoustic trainer it cost 14GB RAM and keep increasing. How to fix this? Thank you
![Screenshot from 2021-10-27 14-40-13](https://user-images.githubusercontent.com/49090718/139021547-751154d4-741a-4fc9-be2c-337005a92db5.png)

**Comment by lethanhson9901** [comment]
I've tried to decrease batch size to 16 but it's not work

**Comment by NTT123** [comment]
There are two ways to resolve this issue:

- use machines with more RAM. Google Colab allows users to select machine with more RAM at `Runtime -> Change runtime type`
- modify the following function to prevent it loading all data to memory.

https://github.com/NTT123/vietTTS/blob/346d46798ab066014b64d971be0735f3f3019703/vietTTS/nat/data_loader.py#L85

**Comment by lethanhson9901** [comment]
How about this solution: shuffle data and divide into 2-3 part and training sequentially each part ? 
Does this solution lead to worse result or not ?
