### ISSUE TITLE
Feature: UnivNet implementation

### ISSUE THREAD

**Issue by lethanhson9901** [NTT123/vietTTS#15]
Thanks for your great work!
I want to implement univnet vocoder but your model is written in  haiku and jax numpy. 
https://github.com/mindslab-ai/univnet

I followed your convert code but got stuck: 
![image](https://user-images.githubusercontent.com/49090718/144012191-759a9261-7f6f-46d5-8bd9-30bd377720c7.png)
jax numpy has no function _unfold_ or _to_ or _transpose_ ?

How can I fix that problems ?

**Comment by NTT123** [comment]
If I were you, I would use the pytorch implementation instead of reimplementing the model in haiku/jax.
You will need to convert the predicted mel spectrogram to pytorch's tensor for your vocoder model.

An example:

```python
mel = HaikuTacotron(text)
mel = jax.device_get(mel)
mel = torch.from_numpy(mel)
wav = TorchVocoder(mel)
```

**Comment by Lethanhson9901** [comment]
Output shape of Acoustic model is : x = [1 151 80]
But  shape of input in Vocoder is: [1 80 151]
How to fix this ?  I also tried to reshape tensor from [1 151 80] to [1 80 151] by _torch,reshape_ but it's didn't work.

**Comment by lethanhson9901** [comment]
Ah, thank you! All done!
