### ISSUE TITLE
mfa version

### ISSUE THREAD

**Issue by MostafaAlaviyan** [NTT123/vietTTS#17]
hi
I want to train fastspeech2 on a Persian dataset with durations extracted from MFA. which version of mfa do U use for training? do you have any preprocessing on your datasets?

**Comment by lethanhson9901** [comment]
You can install MFA via pip: https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html
I don't think version of MFA is affected in this situation.
preprocessing data of him is here: https://colab.research.google.com/gist/NTT123/c99b5a391af56e0cb8f7b190d3d7f0ee/infore-mfa-example.ipynb

**Comment by NTT123** [comment]
Closed due to inactivity.
