### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement jaxlib 

### ISSUE THREAD

**Issue by hovanla** [NTT123/vietTTS#19]
ERROR: Could not find a version that satisfies the requirement jaxlib (from viettts) (from versions: none)
ERROR: No matching distribution found for jaxlib

**Comment by NTT123** [comment]
I think this issue and #16 are all related to JAX installation. My advice is to visit https://github.com/google/jax#installation for instructions.

**Comment by NTT123** [comment]
Closed due to inactivity.
