### ISSUE TITLE
[Gen Loss and Mel-Spec Error]

### ISSUE THREAD

**Issue by TruongThuyLiem** [NTT123/vietTTS#3]
Hi , 
Could you share with me about your Gen Loss and Mel-Spec Error when you got the final model?
I'm trying to train on another dataset for around 3 days and I see loss, error decrease but the quality voice when testing is quite creepy :))))))) 
Thank you so much, I hope you can see my question

**Comment by NTT123** [comment]
For reference, here is a generated mel from the acoustic model at training step 602000:
![mel_602000 (1)](https://user-images.githubusercontent.com/9960521/122044352-fcbc6080-ce0e-11eb-9d01-e1c06cd096d8.png)

I also got a similar ~~Gen~~ mel-spec loss as in the original HiFi-Gan implementation at
https://github.com/jik876/hifi-gan/blob/master/validation_loss.png
